# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x07gateway\"3\n\rPromptRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x13\n\x0buser_prompt\x18\x02 \x01(\t\",\n\x0ePromptResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x02\x32N\n\nLLMService\x12@\n\rExecutePrompt\x12\x16.gateway.PromptRequest\x1a\x17.gateway.PromptResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROMPTREQUEST']._serialized_start=26
  _globals['_PROMPTREQUEST']._serialized_end=77
  _globals['_PROMPTRESPONSE']._serialized_start=79
  _globals['_PROMPTRESPONSE']._serialized_end=123
  _globals['_LLMSERVICE']._serialized_start=125
  _globals['_LLMSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
